import { 
  User, 
  StudentProfile, 
  JobListing, 
  JobApplication, 
  RejectionFeedbackRecord, 
  AuditLog, 
  ApifyScraperConfig, 
  LmsSyncConfig,
  AtsSyncConfig 
} from '../../src/types.ts';

export const INITIAL_USERS: User[] = [
  // 1. EXACTLY ONE ROOT MAIN ADMIN (Rule FR-01: No second Main Admin can exist)
  {
    id: 'user-root-admin',
    email: 'admin@haca.edu',
    fullName: 'Executive Administrator (HACA Root)',
    role: 'MAIN_ADMIN',
    department: 'Central Administration & Governance',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  // 2. PLACEMENT OFFICERS (Operations & Corporate Relations)
  {
    id: 'user-po-1',
    email: 'placement.asad@haca.edu',
    fullName: 'Asad Rizvi',
    role: 'PLACEMENT_OFFICER',
    department: 'Career & Industry Relations',
    isActive: true,
    createdAt: '2026-01-05T08:00:00Z',
  },
  {
    id: 'user-po-2',
    email: 'placement.maya@haca.edu',
    fullName: 'Maya Lin',
    role: 'PLACEMENT_OFFICER',
    department: 'Tech Placements & Corporate Sourcing',
    isActive: true,
    createdAt: '2026-01-05T08:00:00Z',
  },
  {
    id: 'user-po-3',
    email: 'placement.tariq@haca.edu',
    fullName: 'Tariq Ahmed',
    role: 'PLACEMENT_OFFICER',
    department: 'Industry Partnerships & Matching',
    isActive: true,
    createdAt: '2026-01-06T08:00:00Z',
  },
  // 3. MANAGEMENT (Executive Analytics & Governance)
  {
    id: 'user-mgmt-1',
    email: 'director.vance@haca.edu',
    fullName: 'Dr. Kamran Vance',
    role: 'MANAGEMENT',
    department: 'Executive Board of Directors',
    isActive: true,
    createdAt: '2026-01-02T10:00:00Z',
  },
  {
    id: 'user-mgmt-2',
    email: 'dean.eleanor@haca.edu',
    fullName: 'Dr. Eleanor Vance',
    role: 'MANAGEMENT',
    department: 'Dean of Academic Governance',
    isActive: true,
    createdAt: '2026-01-03T10:00:00Z',
  },
  {
    id: 'user-mgmt-3',
    email: 'trustee.rehan@haca.edu',
    fullName: 'Rehan Siddiqui',
    role: 'MANAGEMENT',
    department: 'Board Placement Trustee',
    isActive: true,
    createdAt: '2026-01-04T10:00:00Z',
  },
  // 4. STUDENTS
  {
    id: 'student-tech-1',
    email: 'ali.raza@student.haca.edu',
    fullName: 'Ali Raza',
    role: 'STUDENT',
    department: 'School of Tech',
    isActive: true,
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'student-tech-2',
    email: 'zainab.khan@student.haca.edu',
    fullName: 'Zainab Khan',
    role: 'STUDENT',
    department: 'School of Tech',
    isActive: true,
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'student-tech-3',
    email: 'hamza.sheikh@student.haca.edu',
    fullName: 'Hamza Sheikh',
    role: 'STUDENT',
    department: 'School of Tech',
    isActive: true,
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'student-design-1',
    email: 'fatima.noor@student.haca.edu',
    fullName: 'Fatima Noor',
    role: 'STUDENT',
    department: 'School of Design',
    isActive: true,
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'student-design-2',
    email: 'omar.farooq@student.haca.edu',
    fullName: 'Omar Farooq',
    role: 'STUDENT',
    department: 'School of Design',
    isActive: true,
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'student-mkt-1',
    email: 'bilal.ahmed@student.haca.edu',
    fullName: 'Bilal Ahmed',
    role: 'STUDENT',
    department: 'School of Marketing',
    isActive: true,
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'student-mkt-2',
    email: 'ayesha.malik@student.haca.edu',
    fullName: 'Ayesha Malik',
    role: 'STUDENT',
    department: 'School of Marketing',
    isActive: true,
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'student-data-1',
    email: 'arjun.kumar@student.haca.edu',
    fullName: 'Arjun Kumar',
    role: 'STUDENT',
    department: 'School of Tech',
    isActive: true,
    createdAt: '2026-01-15T00:00:00Z',
  }
];

export const INITIAL_STUDENTS: StudentProfile[] = [
  // Student 1: Tech, Eligible, active job seeker (Test Student 1)
  {
    id: 'student-tech-1',
    registrationNo: 'HACA-2025-TC-014',
    fullName: 'Ali Raza',
    email: 'ali.raza@student.haca.edu',
    phone: '+92 300 4581290',
    school: 'School of Tech',
    program: 'Full Stack Web Development',
    designation: 'Full Stack Developer',
    yearsOfExperience: 1,
    batch: '2025-Q4',
    mentorId: 'user-mentor-1',
    mentorName: 'Dr. Salman Tariq',
    eligibilityStatus: 'ELIGIBLE',
    eligibilityUpdatedAt: '2026-02-01T10:00:00Z',
    eligibilityUpdatedBy: 'Dr. Salman Tariq',
    evaluationNotes: 'Exceptional performance in React & Node.js modules. Completed Capstone project ahead of time. High attendance.',
    resumeUrl: 'https://cdn.haca.edu/resumes/ali-raza-2026.pdf',
    portfolioUrl: 'https://aliraza-dev.portfolio.io',
    linkedinUrl: 'https://linkedin.com/in/aliraza-haca',
    academic: {
      course: 'MERN Stack Engineering',
      scores: {
        gpaOrPercentage: 91.5,
        assignmentsCompleted: 24,
        totalAssignments: 24,
        capstoneScore: 95
      },
      attendancePercentage: 94.0,
      skills: ['React', 'Node.js', 'JavaScript', 'SQL', 'TypeScript', 'Express', 'PostgreSQL', 'Tailwind CSS', 'Git', 'REST APIs'],
      projects: [
        {
          id: 'proj-1',
          title: 'Enterprise CRM System',
          description: 'Multi-tenant CRM with role-based access control and analytics dashboard.',
          status: 'COMPLETED',
          grade: 'A+',
          githubUrl: 'https://github.com/aliraza/enterprise-crm'
        },
        {
          id: 'proj-2',
          title: 'Cloud Document Vault',
          description: 'Secure file upload and metadata search microservice using AWS S3 & Docker.',
          status: 'COMPLETED',
          grade: 'A',
          githubUrl: 'https://github.com/aliraza/cloud-doc-vault'
        }
      ],
      readinessGaps: {
        missingSkills: ['Docker', 'AWS basics'],
        missingProjects: [],
        attendanceWarning: false
      }
    },
    inactivityFlags: {
      hasNotApplied: false,
      consecutiveRejections: 0,
      noInterviewFollowUp: false
    },
    createdAt: '2026-01-15T00:00:00Z'
  },
  // Student 2: Tech, Eligible with a rejection needing remedial action
  {
    id: 'student-tech-2',
    registrationNo: 'HACA-2025-TC-022',
    fullName: 'Zainab Khan',
    email: 'zainab.khan@student.haca.edu',
    phone: '+92 321 8845112',
    school: 'School of Tech',
    program: 'Full Stack Web Development',
    designation: 'Frontend Developer',
    yearsOfExperience: 1,
    batch: '2025-Q4',
    mentorId: 'user-mentor-1',
    mentorName: 'Dr. Salman Tariq',
    eligibilityStatus: 'ELIGIBLE',
    eligibilityUpdatedAt: '2026-02-05T14:30:00Z',
    eligibilityUpdatedBy: 'Dr. Salman Tariq',
    evaluationNotes: 'Solid core skills. Needs practice in technical interview communication under pressure.',
    resumeUrl: 'https://cdn.haca.edu/resumes/zainab-khan-2026.pdf',
    portfolioUrl: 'https://zainabkhan.tech',
    linkedinUrl: 'https://linkedin.com/in/zainab-khan-dev',
    academic: {
      course: 'MERN Stack Engineering',
      scores: {
        gpaOrPercentage: 86.0,
        assignmentsCompleted: 22,
        totalAssignments: 24,
        capstoneScore: 88
      },
      attendancePercentage: 89.2,
      skills: ['React', 'JavaScript', 'HTML5', 'CSS3', 'Node.js', 'MongoDB', 'Git'],
      projects: [
        {
          id: 'proj-3',
          title: 'E-Commerce Marketplace',
          description: 'Full-stack store with Stripe integration and inventory management.',
          status: 'COMPLETED',
          grade: 'A',
          githubUrl: 'https://github.com/zainab/ecommerce-market'
        }
      ],
      readinessGaps: {
        missingSkills: ['TypeScript', 'SQL'],
        missingProjects: ['Second advanced portfolio piece'],
        attendanceWarning: false
      }
    },
    inactivityFlags: {
      hasNotApplied: false,
      consecutiveRejections: 1,
      noInterviewFollowUp: false
    },
    createdAt: '2026-01-15T00:00:00Z'
  },
  // Student 3: Tech, Python Developer (Test Student 2)
  {
    id: 'student-tech-3',
    registrationNo: 'HACA-2026-TC-003',
    fullName: 'Hamza Sheikh',
    email: 'hamza.sheikh@student.haca.edu',
    phone: '+92 345 7712390',
    school: 'School of Tech',
    program: 'Python Development',
    designation: 'Python Developer',
    yearsOfExperience: 1,
    batch: '2026-Q1',
    mentorId: 'user-mentor-1',
    mentorName: 'Dr. Salman Tariq',
    eligibilityStatus: 'ELIGIBLE',
    eligibilityUpdatedAt: '2026-02-14T10:00:00Z',
    evaluationNotes: 'Strong Python and Django backend skills. Capstone completed successfully.',
    resumeUrl: 'https://cdn.haca.edu/resumes/hamza-sheikh-python.pdf',
    academic: {
      course: 'Python & Backend Architecture',
      scores: {
        gpaOrPercentage: 85.5,
        assignmentsCompleted: 22,
        totalAssignments: 24,
        capstoneScore: 88
      },
      attendancePercentage: 88.0,
      skills: ['Python', 'Django', 'SQL', 'Git', 'REST APIs', 'PostgreSQL'],
      projects: [
        {
          id: 'proj-4',
          title: 'Task Management App',
          description: 'Scalable Django REST backend with JWT authentication.',
          status: 'COMPLETED'
        }
      ],
      readinessGaps: {
        missingSkills: [],
        missingProjects: [],
        attendanceWarning: false
      }
    },
    inactivityFlags: {
      hasNotApplied: false,
      consecutiveRejections: 0,
      noInterviewFollowUp: false
    },
    createdAt: '2026-01-15T00:00:00Z'
  },
  // Student 4: Design, Eligible, Placed!
  {
    id: 'student-design-1',
    registrationNo: 'HACA-2025-DS-009',
    fullName: 'Fatima Noor',
    email: 'fatima.noor@student.haca.edu',
    phone: '+92 333 9128471',
    school: 'School of Design',
    program: 'UI/UX Product Design',
    designation: 'UI/UX Designer',
    yearsOfExperience: 1,
    batch: '2025-Q4',
    mentorId: 'user-mentor-2',
    mentorName: 'Sarah Jenkins',
    eligibilityStatus: 'ELIGIBLE',
    eligibilityUpdatedAt: '2026-01-28T11:00:00Z',
    eligibilityUpdatedBy: 'Sarah Jenkins',
    evaluationNotes: 'Outstanding portfolio. Strong design systems experience and user research methodology.',
    resumeUrl: 'https://cdn.haca.edu/resumes/fatima-noor-design.pdf',
    portfolioUrl: 'https://fatimanoor.design',
    linkedinUrl: 'https://linkedin.com/in/fatima-noor-uiux',
    academic: {
      course: 'Product Design & Design Systems',
      scores: {
        gpaOrPercentage: 94.0,
        assignmentsCompleted: 20,
        totalAssignments: 20,
        capstoneScore: 96
      },
      attendancePercentage: 96.5,
      skills: ['Figma', 'User Research', 'Design Systems', 'Prototyping', 'Wireframing', 'Usability Testing'],
      projects: [
        {
          id: 'proj-5',
          title: 'FinTech Mobile App Redesign',
          description: 'Complete user flow overhaul resulting in 40% reduction in checkout drop-off.',
          status: 'COMPLETED',
          grade: 'A+'
        }
      ],
      readinessGaps: {
        missingSkills: [],
        missingProjects: [],
        attendanceWarning: false
      }
    },
    inactivityFlags: {
      hasNotApplied: false,
      consecutiveRejections: 0,
      noInterviewFollowUp: false
    },
    createdAt: '2026-01-15T00:00:00Z'
  },
  // Student 5: Design, Ineligible (Attendance gap)
  {
    id: 'student-design-2',
    registrationNo: 'HACA-2025-DS-031',
    fullName: 'Omar Farooq',
    email: 'omar.farooq@student.haca.edu',
    phone: '+92 311 6721098',
    school: 'School of Design',
    program: 'UI/UX Product Design',
    designation: 'UI/UX Designer',
    yearsOfExperience: 0.5,
    batch: '2025-Q4',
    mentorId: 'user-mentor-2',
    mentorName: 'Sarah Jenkins',
    eligibilityStatus: 'NOT_ELIGIBLE',
    eligibilityUpdatedAt: '2026-02-10T16:00:00Z',
    eligibilityUpdatedBy: 'Sarah Jenkins',
    evaluationNotes: 'Incomplete project submissions and low attendance (68%). Must complete remedial assignments before re-evaluation.',
    academic: {
      course: 'Product Design & Design Systems',
      scores: {
        gpaOrPercentage: 62.0,
        assignmentsCompleted: 11,
        totalAssignments: 20,
        capstoneScore: undefined
      },
      attendancePercentage: 68.0,
      skills: ['Figma Basics', 'Wireframing'],
      projects: [],
      readinessGaps: {
        missingSkills: ['Design Systems', 'Usability Testing', 'Prototyping'],
        missingProjects: ['Capstone Case Study'],
        attendanceWarning: true
      }
    },
    inactivityFlags: {
      hasNotApplied: true,
      consecutiveRejections: 0,
      noInterviewFollowUp: false
    },
    createdAt: '2026-01-15T00:00:00Z'
  },
  // Student 6: Marketing, Admin Override example
  {
    id: 'student-mkt-1',
    registrationNo: 'HACA-2025-MK-005',
    fullName: 'Bilal Ahmed',
    email: 'bilal.ahmed@student.haca.edu',
    phone: '+92 301 2289415',
    school: 'School of Marketing',
    program: 'Growth & Digital Marketing',
    designation: 'Growth Marketing Specialist',
    yearsOfExperience: 2,
    batch: '2025-Q3',
    mentorId: 'user-mentor-1',
    mentorName: 'Dr. Salman Tariq',
    eligibilityStatus: 'ADMIN_OVERRIDE',
    eligibilityUpdatedAt: '2026-02-12T09:15:00Z',
    eligibilityUpdatedBy: 'Executive Administrator (HACA Root)',
    overrideReason: 'Prior agency experience validated by HACA Career Advisory Board; fast-tracked to placement pool.',
    resumeUrl: 'https://cdn.haca.edu/resumes/bilal-ahmed-mkt.pdf',
    portfolioUrl: 'https://bilalahmedgrowth.com',
    academic: {
      course: 'Performance Marketing & SEO',
      scores: {
        gpaOrPercentage: 88.0,
        assignmentsCompleted: 19,
        totalAssignments: 20,
        capstoneScore: 90
      },
      attendancePercentage: 86.5,
      skills: ['SEO', 'Google Ads', 'Meta Ads', 'Analytics', 'Content Strategy', 'HubSpot'],
      projects: [
        {
          id: 'proj-6',
          title: 'SaaS Lead Gen Campaign',
          description: 'Achieved $18 CPA for B2B analytics tool using multi-channel funnel.',
          status: 'COMPLETED',
          grade: 'A'
        }
      ],
      readinessGaps: {
        missingSkills: ['SQL for Marketing'],
        missingProjects: [],
        attendanceWarning: false
      }
    },
    inactivityFlags: {
      hasNotApplied: false,
      consecutiveRejections: 0,
      noInterviewFollowUp: false
    },
    createdAt: '2026-01-15T00:00:00Z'
  },
  // Student 7: Tech, Data Analyst (Test Student 3)
  {
    id: 'student-data-1',
    registrationNo: 'HACA-2025-DA-011',
    fullName: 'Arjun Kumar',
    email: 'arjun.kumar@student.haca.edu',
    phone: '+92 322 5519823',
    school: 'School of Tech',
    program: 'Data Analytics',
    designation: 'Data Analyst',
    yearsOfExperience: 1,
    batch: '2025-Q4',
    mentorId: 'user-mentor-1',
    mentorName: 'Dr. Salman Tariq',
    eligibilityStatus: 'ELIGIBLE',
    eligibilityUpdatedAt: '2026-02-10T10:00:00Z',
    evaluationNotes: 'Proficient with SQL, Python, Excel, and Power BI dashboards. High analytical acumen.',
    resumeUrl: 'https://cdn.haca.edu/resumes/arjun-kumar-data.pdf',
    academic: {
      course: 'Data Analytics & Business Intelligence',
      scores: {
        gpaOrPercentage: 89.5,
        assignmentsCompleted: 22,
        totalAssignments: 24,
        capstoneScore: 92
      },
      attendancePercentage: 92.0,
      skills: ['Python', 'SQL', 'Excel', 'Power BI', 'Tableau', 'Data Analysis'],
      projects: [
        {
          id: 'proj-7',
          title: 'E-Commerce Sales Insights Dashboard',
          description: 'End-to-end Power BI report with automated SQL ETL pipelines.',
          status: 'COMPLETED',
          grade: 'A'
        }
      ],
      readinessGaps: {
        missingSkills: [],
        missingProjects: [],
        attendanceWarning: false
      }
    },
    inactivityFlags: {
      hasNotApplied: false,
      consecutiveRejections: 0,
      noInterviewFollowUp: false
    },
    createdAt: '2026-01-15T00:00:00Z'
  }
];

export const INITIAL_JOBS: JobListing[] = [
  {
    id: 'job-haca-101',
    jobCode: 'JOB-2026-001',
    title: 'Full Stack Developer',
    company: 'Apex Software Labs',
    location: 'Bangalore, Karnataka, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹8,00,000 - ₹13,00,000 / annum',
    description: 'Build modern full-stack web applications using React, TypeScript, and Node.js with microservices architecture.',
    requiredSkills: ["React","TypeScript","Node.js","SQL"],
    preferredSkills: ["PostgreSQL","Docker","Tailwind CSS","Git"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Full Stack Development',
    normalizedDesignation: 'Full Stack Developer',
    sourceChannel: 'AI_JOB_SCRAPER',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Full%20Stack%20Developer%20Apex%20Software%20Labs',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Full%20Stack%20Developer%20Apex%20Software%20Labs',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 0 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 0 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 0 * 3600000).toISOString()
  },
  {
    id: 'job-haca-102',
    jobCode: 'JOB-2026-002',
    title: 'MERN Stack Developer',
    company: 'NovaTech Digital',
    location: 'Kochi, Kerala, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹7,50,000 - ₹11,50,000 / annum',
    description: 'Develop modern end-to-end web applications with MongoDB, Express, React, and Node.js.',
    requiredSkills: ["MongoDB","Express","React","Node.js"],
    preferredSkills: ["Redux","REST APIs","Git","Tailwind CSS"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Full Stack Development',
    normalizedDesignation: 'Full Stack Developer',
    sourceChannel: 'ATS_JOB_API',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=MERN%20Stack%20Developer%20NovaTech%20Digital',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=MERN%20Stack%20Developer%20NovaTech%20Digital',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 10 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 3600000).toISOString()
  },
  {
    id: 'job-haca-103',
    jobCode: 'JOB-2026-003',
    title: 'Junior Full Stack Engineer',
    company: 'DataStream Systems',
    location: 'Hyderabad, Telangana, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹6,50,000 - ₹9,50,000 / annum',
    description: 'Join an agile product engineering squad delivering user-facing features across frontend and backend.',
    requiredSkills: ["JavaScript","React","Node.js","PostgreSQL"],
    preferredSkills: ["TypeScript","Git","HTML5","CSS3"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Full Stack Development',
    normalizedDesignation: 'Full Stack Developer',
    sourceChannel: 'PLACEMENT_DIRECT',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Junior%20Full%20Stack%20Engineer%20DataStream%20Systems',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Junior%20Full%20Stack%20Engineer%20DataStream%20Systems',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 20 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 20 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 3600000).toISOString()
  },
  {
    id: 'job-haca-104',
    jobCode: 'JOB-2026-004',
    title: 'Software Engineer - Full Stack',
    company: 'Vanguard Analytics',
    location: 'Pune, Maharashtra, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹9,00,000 - ₹14,00,000 / annum',
    description: 'Architect and implement scalable web applications and RESTful APIs serving millions of active users.',
    requiredSkills: ["React","Node.js","TypeScript","REST APIs"],
    preferredSkills: ["Docker","SQL","Git","AWS"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Full Stack Development',
    normalizedDesignation: 'Full Stack Developer',
    sourceChannel: 'AI_JOB_SCRAPER',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Software%20Engineer%20-%20Full%20Stack%20Vanguard%20Analytics',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Software%20Engineer%20-%20Full%20Stack%20Vanguard%20Analytics',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 30 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 3600000).toISOString()
  },
  {
    id: 'job-haca-105',
    jobCode: 'JOB-2026-005',
    title: 'Full Stack Web Developer',
    company: 'PixelCraft Studio',
    location: 'Chennai, Tamil Nadu, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹7,00,000 - ₹10,50,000 / annum',
    description: 'Full-stack engineering role focusing on responsive interfaces, backend business logic, and database schemas.',
    requiredSkills: ["React","JavaScript","Node.js","SQL"],
    preferredSkills: ["TypeScript","Tailwind CSS","Git"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Full Stack Development',
    normalizedDesignation: 'Full Stack Developer',
    sourceChannel: 'ATS_JOB_API',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Full%20Stack%20Web%20Developer%20PixelCraft%20Studio',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Full%20Stack%20Web%20Developer%20PixelCraft%20Studio',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 40 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 40 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 3600000).toISOString()
  },
  {
    id: 'job-haca-106',
    jobCode: 'JOB-2026-006',
    title: 'Associate Full Stack Developer',
    company: 'InfyCloud Technologies',
    location: 'Mumbai, Maharashtra, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹6,00,000 - ₹8,50,000 / annum',
    description: 'Entry-level full stack position developing API endpoints, UI views, and integrating cloud database stores.',
    requiredSkills: ["React","Express","Node.js","MongoDB"],
    preferredSkills: ["Git","REST APIs","PostgreSQL"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Full Stack Development',
    normalizedDesignation: 'Full Stack Developer',
    sourceChannel: 'PLACEMENT_DIRECT',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Associate%20Full%20Stack%20Developer%20InfyCloud%20Technologies',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Associate%20Full%20Stack%20Developer%20InfyCloud%20Technologies',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 50 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 50 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 50 * 3600000).toISOString()
  },
  {
    id: 'job-haca-107',
    jobCode: 'JOB-2026-007',
    title: 'Full Stack Engineer (React / Python)',
    company: 'CyberNet Solutions',
    location: 'Gurugram, Haryana, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹8,50,000 - ₹12,50,000 / annum',
    description: 'Build high-performance web products combining React frontend with Python/FastAPI microservices.',
    requiredSkills: ["React","Python","FastAPI","SQL"],
    preferredSkills: ["PostgreSQL","Docker","TypeScript"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development","Python Development"],
    category: 'Full Stack Development',
    normalizedDesignation: 'Full Stack Developer',
    sourceChannel: 'AI_JOB_SCRAPER',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Full%20Stack%20Engineer%20(React%20%2F%20Python)%20CyberNet%20Solutions',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Full%20Stack%20Engineer%20(React%20%2F%20Python)%20CyberNet%20Solutions',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 60 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 60 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 3600000).toISOString()
  },
  {
    id: 'job-haca-108',
    jobCode: 'JOB-2026-008',
    title: 'Full Stack Application Engineer',
    company: 'ZetaWave Labs',
    location: 'Noida, Uttar Pradesh, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹8,00,000 - ₹12,00,000 / annum',
    description: 'Develop end-to-end features, optimize relational databases, and collaborate with product teams.',
    requiredSkills: ["React","TypeScript","Node.js","PostgreSQL"],
    preferredSkills: ["Docker","Git","Tailwind CSS"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Full Stack Development',
    normalizedDesignation: 'Full Stack Developer',
    sourceChannel: 'ATS_JOB_API',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Full%20Stack%20Application%20Engineer%20ZetaWave%20Labs',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Full%20Stack%20Application%20Engineer%20ZetaWave%20Labs',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 70 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 70 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 70 * 3600000).toISOString()
  },
  {
    id: 'job-haca-109',
    jobCode: 'JOB-2026-009',
    title: 'Full Stack Developer (Next.js & Node)',
    company: 'Thoughtworks India',
    location: 'Remote - India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹8,50,000 - ₹13,00,000 / annum',
    description: 'Work on high-speed server-rendered web applications with Next.js, Node.js, and modern TypeScript.',
    requiredSkills: ["Next.js","React","Node.js","TypeScript"],
    preferredSkills: ["Tailwind CSS","SQL","Git"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Full Stack Development',
    normalizedDesignation: 'Full Stack Developer',
    sourceChannel: 'PLACEMENT_DIRECT',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Full%20Stack%20Developer%20(Next.js%20%26%20Node)%20Thoughtworks%20India',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Full%20Stack%20Developer%20(Next.js%20%26%20Node)%20Thoughtworks%20India',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 80 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 80 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 80 * 3600000).toISOString()
  },
  {
    id: 'job-haca-110',
    jobCode: 'JOB-2026-010',
    title: 'Full Stack Software Developer',
    company: 'Freshworks India',
    location: 'Thiruvananthapuram, Kerala, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹7,00,000 - ₹11,00,000 / annum',
    description: 'Build scalable full-stack web solutions from wireframes to cloud deployment.',
    requiredSkills: ["React","Node.js","SQL","Git"],
    preferredSkills: ["JavaScript","Docker","REST APIs"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Full Stack Development',
    normalizedDesignation: 'Full Stack Developer',
    sourceChannel: 'AI_JOB_SCRAPER',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Full%20Stack%20Software%20Developer%20Freshworks%20India',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Full%20Stack%20Software%20Developer%20Freshworks%20India',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 90 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 90 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 90 * 3600000).toISOString()
  },
  {
    id: 'job-haca-111',
    jobCode: 'JOB-2026-011',
    title: 'Frontend React Developer',
    company: 'Zoho Corporation',
    location: 'Kozhikode, Kerala, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹6,00,000 - ₹9,50,000 / annum',
    description: 'Join our frontend engineering team building responsive, highly dynamic user interfaces with React.',
    requiredSkills: ["React","JavaScript","HTML5","CSS3"],
    preferredSkills: ["TypeScript","Tailwind CSS","Next.js","Figma"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Frontend Development',
    normalizedDesignation: 'Frontend Developer',
    sourceChannel: 'ATS_JOB_API',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Frontend%20React%20Developer%20Zoho%20Corporation',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Frontend%20React%20Developer%20Zoho%20Corporation',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 100 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 100 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 100 * 3600000).toISOString()
  },
  {
    id: 'job-haca-112',
    jobCode: 'JOB-2026-012',
    title: 'React.js Developer',
    company: 'Swiggy Tech',
    location: 'Ernakulam, Kerala, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹7,50,000 - ₹11,00,000 / annum',
    description: 'Build high-performance web dashboards with React.js, TypeScript, and state management.',
    requiredSkills: ["React","TypeScript","Tailwind CSS","Redux"],
    preferredSkills: ["Next.js","Jest","Git","REST APIs"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Frontend Development',
    normalizedDesignation: 'Frontend Developer',
    sourceChannel: 'PLACEMENT_DIRECT',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=React.js%20Developer%20Swiggy%20Tech',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=React.js%20Developer%20Swiggy%20Tech',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 110 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 110 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 110 * 3600000).toISOString()
  },
  {
    id: 'job-haca-113',
    jobCode: 'JOB-2026-013',
    title: 'UI Developer',
    company: 'Razorpay Labs',
    location: 'Bangalore, Karnataka, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹5,50,000 - ₹8,50,000 / annum',
    description: 'Translate Figma UI wireframes into responsive, accessible, cross-browser web interfaces.',
    requiredSkills: ["JavaScript","HTML5","CSS3","React"],
    preferredSkills: ["Figma","Tailwind CSS","Git"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development","UI/UX Product Design"],
    category: 'Frontend Development',
    normalizedDesignation: 'Frontend Developer',
    sourceChannel: 'AI_JOB_SCRAPER',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=UI%20Developer%20Razorpay%20Labs',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=UI%20Developer%20Razorpay%20Labs',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 120 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 120 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 120 * 3600000).toISOString()
  },
  {
    id: 'job-haca-114',
    jobCode: 'JOB-2026-014',
    title: 'Frontend Web Developer',
    company: 'Meesho Engineering',
    location: 'Kochi, Kerala, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹6,50,000 - ₹10,00,000 / annum',
    description: 'Engineer modern web applications focusing on fast page loads, clean UI components, and SEO.',
    requiredSkills: ["React","JavaScript","Next.js","Tailwind CSS"],
    preferredSkills: ["TypeScript","Git","REST APIs"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Frontend Development',
    normalizedDesignation: 'Frontend Developer',
    sourceChannel: 'ATS_JOB_API',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Frontend%20Web%20Developer%20Meesho%20Engineering',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Frontend%20Web%20Developer%20Meesho%20Engineering',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 130 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 130 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 130 * 3600000).toISOString()
  },
  {
    id: 'job-haca-115',
    jobCode: 'JOB-2026-015',
    title: 'Junior Frontend Developer',
    company: 'CRED Tech',
    location: 'Hyderabad, Telangana, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹5,00,000 - ₹7,50,000 / annum',
    description: 'Develop responsive client-side pages and components using React and modern CSS.',
    requiredSkills: ["React","HTML5","CSS3","JavaScript"],
    preferredSkills: ["Git","Tailwind CSS","TypeScript"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Frontend Development',
    normalizedDesignation: 'Frontend Developer',
    sourceChannel: 'PLACEMENT_DIRECT',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Junior%20Frontend%20Developer%20CRED%20Tech',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Junior%20Frontend%20Developer%20CRED%20Tech',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 140 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 140 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 140 * 3600000).toISOString()
  },
  {
    id: 'job-haca-116',
    jobCode: 'JOB-2026-016',
    title: 'Frontend Engineer (React / TypeScript)',
    company: 'InMobi Digital',
    location: 'Pune, Maharashtra, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹8,00,000 - ₹12,00,000 / annum',
    description: 'Create scalable, modular design systems and accessible user interfaces for enterprise web portals.',
    requiredSkills: ["React","TypeScript","Tailwind CSS","Git"],
    preferredSkills: ["Next.js","REST APIs","Redux"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Frontend Development',
    normalizedDesignation: 'Frontend Developer',
    sourceChannel: 'AI_JOB_SCRAPER',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Frontend%20Engineer%20(React%20%2F%20TypeScript)%20InMobi%20Digital',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Frontend%20Engineer%20(React%20%2F%20TypeScript)%20InMobi%20Digital',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 150 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 150 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 150 * 3600000).toISOString()
  },
  {
    id: 'job-haca-117',
    jobCode: 'JOB-2026-017',
    title: 'Web Frontend Developer',
    company: 'Groww Labs',
    location: 'Chennai, Tamil Nadu, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹6,00,000 - ₹9,00,000 / annum',
    description: 'Build cross-platform web experiences and interactive forms for customer-facing web applications.',
    requiredSkills: ["JavaScript","React","HTML5","CSS3"],
    preferredSkills: ["Bootstrap","Git","Tailwind CSS"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Frontend Development',
    normalizedDesignation: 'Frontend Developer',
    sourceChannel: 'ATS_JOB_API',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Web%20Frontend%20Developer%20Groww%20Labs',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Web%20Frontend%20Developer%20Groww%20Labs',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 160 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 160 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 160 * 3600000).toISOString()
  },
  {
    id: 'job-haca-118',
    jobCode: 'JOB-2026-018',
    title: 'Frontend Software Engineer',
    company: 'Zerodha Tech',
    location: 'Mumbai, Maharashtra, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹8,50,000 - ₹12,50,000 / annum',
    description: 'Design and optimize core frontend architecture, state management, and real-time UI data streams.',
    requiredSkills: ["React","TypeScript","Next.js","REST APIs"],
    preferredSkills: ["Git","GraphQL","Tailwind CSS"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Frontend Development',
    normalizedDesignation: 'Frontend Developer',
    sourceChannel: 'PLACEMENT_DIRECT',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Frontend%20Software%20Engineer%20Zerodha%20Tech',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Frontend%20Software%20Engineer%20Zerodha%20Tech',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 170 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 170 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 170 * 3600000).toISOString()
  },
  {
    id: 'job-haca-119',
    jobCode: 'JOB-2026-019',
    title: 'React & Next.js Engineer',
    company: 'Postman Software',
    location: 'Gurugram, Haryana, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹8,00,000 - ₹11,50,000 / annum',
    description: 'Develop server-rendered React applications with optimal Core Web Vitals and polished aesthetics.',
    requiredSkills: ["React","Next.js","TypeScript","Tailwind CSS"],
    preferredSkills: ["Jest","Figma","Git"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Frontend Development',
    normalizedDesignation: 'Frontend Developer',
    sourceChannel: 'AI_JOB_SCRAPER',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=React%20%26%20Next.js%20Engineer%20Postman%20Software',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=React%20%26%20Next.js%20Engineer%20Postman%20Software',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 180 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 180 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 180 * 3600000).toISOString()
  },
  {
    id: 'job-haca-120',
    jobCode: 'JOB-2026-020',
    title: 'Associate React Developer',
    company: 'Hasura Tech',
    location: 'Noida, Uttar Pradesh, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹5,50,000 - ₹8,00,000 / annum',
    description: 'Entry-level frontend role implementing component libraries, modals, and API integrations in React.',
    requiredSkills: ["React","JavaScript","Tailwind CSS","Git"],
    preferredSkills: ["HTML5","CSS3","REST APIs"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Frontend Development',
    normalizedDesignation: 'Frontend Developer',
    sourceChannel: 'ATS_JOB_API',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Associate%20React%20Developer%20Hasura%20Tech',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Associate%20React%20Developer%20Hasura%20Tech',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 190 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 190 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 190 * 3600000).toISOString()
  },
  {
    id: 'job-haca-121',
    jobCode: 'JOB-2026-021',
    title: 'Backend Python Developer',
    company: 'BrowserStack India',
    location: 'Remote - India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹7,50,000 - ₹11,50,000 / annum',
    description: 'Develop high-performance RESTful APIs, data validation schemas, and database transactions.',
    requiredSkills: ["Python","Django","FastAPI","SQL"],
    preferredSkills: ["PostgreSQL","Docker","Redis","REST APIs"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Python Development","Full Stack Web Development"],
    category: 'Backend Development',
    normalizedDesignation: 'Backend Developer',
    sourceChannel: 'PLACEMENT_DIRECT',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Backend%20Python%20Developer%20BrowserStack%20India',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Backend%20Python%20Developer%20BrowserStack%20India',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 200 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 200 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 200 * 3600000).toISOString()
  },
  {
    id: 'job-haca-122',
    jobCode: 'JOB-2026-022',
    title: 'Python Backend Engineer',
    company: 'CleverTap Labs',
    location: 'Thiruvananthapuram, Kerala, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹8,00,000 - ₹12,50,000 / annum',
    description: 'Build scalable cloud services, backend queues, and clean API endpoints using Python.',
    requiredSkills: ["Python","FastAPI","PostgreSQL","Docker"],
    preferredSkills: ["SQL","Git","Redis","AWS"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Python Development"],
    category: 'Backend Development',
    normalizedDesignation: 'Backend Developer',
    sourceChannel: 'AI_JOB_SCRAPER',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Python%20Backend%20Engineer%20CleverTap%20Labs',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Python%20Backend%20Engineer%20CleverTap%20Labs',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 210 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 210 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 210 * 3600000).toISOString()
  },
  {
    id: 'job-haca-123',
    jobCode: 'JOB-2026-023',
    title: 'Node.js Backend Developer',
    company: 'Delhivery Tech',
    location: 'Kozhikode, Kerala, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹7,50,000 - ₹11,00,000 / annum',
    description: 'Design and build resilient backend microservices using Node.js, Express, and relational databases.',
    requiredSkills: ["Node.js","Express","TypeScript","SQL"],
    preferredSkills: ["PostgreSQL","MongoDB","Docker","REST APIs"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Backend Development',
    normalizedDesignation: 'Backend Developer',
    sourceChannel: 'ATS_JOB_API',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Node.js%20Backend%20Developer%20Delhivery%20Tech',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Node.js%20Backend%20Developer%20Delhivery%20Tech',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 220 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 220 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 220 * 3600000).toISOString()
  },
  {
    id: 'job-haca-124',
    jobCode: 'JOB-2026-024',
    title: 'Junior Backend Engineer',
    company: 'Urban Company',
    location: 'Ernakulam, Kerala, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹6,00,000 - ₹8,50,000 / annum',
    description: 'Write maintainable server-side logic, optimize database queries, and integrate 3rd party APIs.',
    requiredSkills: ["Python","SQL","REST APIs","Git"],
    preferredSkills: ["Django","PostgreSQL","Docker"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Python Development","Full Stack Web Development"],
    category: 'Backend Development',
    normalizedDesignation: 'Backend Developer',
    sourceChannel: 'PLACEMENT_DIRECT',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Junior%20Backend%20Engineer%20Urban%20Company',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Junior%20Backend%20Engineer%20Urban%20Company',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 230 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 230 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 230 * 3600000).toISOString()
  },
  {
    id: 'job-haca-125',
    jobCode: 'JOB-2026-025',
    title: 'Backend Software Developer',
    company: 'Juspay Technologies',
    location: 'Bangalore, Karnataka, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹7,00,000 - ₹10,50,000 / annum',
    description: 'Build backend business services, asynchronous workers, and secure user authorization protocols.',
    requiredSkills: ["Python","SQL","PostgreSQL","Git"],
    preferredSkills: ["FastAPI","Docker","Redis"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Python Development"],
    category: 'Backend Development',
    normalizedDesignation: 'Backend Developer',
    sourceChannel: 'AI_JOB_SCRAPER',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Backend%20Software%20Developer%20Juspay%20Technologies',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Backend%20Software%20Developer%20Juspay%20Technologies',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 240 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 240 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 240 * 3600000).toISOString()
  },
  {
    id: 'job-haca-126',
    jobCode: 'JOB-2026-026',
    title: 'API & Backend Developer',
    company: 'Zepto Engineering',
    location: 'Kochi, Kerala, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹6,50,000 - ₹9,50,000 / annum',
    description: 'Develop robust, documented RESTful APIs powering web and mobile client applications.',
    requiredSkills: ["Node.js","SQL","REST APIs","Git"],
    preferredSkills: ["Express","TypeScript","PostgreSQL"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Backend Development',
    normalizedDesignation: 'Backend Developer',
    sourceChannel: 'ATS_JOB_API',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=API%20%26%20Backend%20Developer%20Zepto%20Engineering',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=API%20%26%20Backend%20Developer%20Zepto%20Engineering',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 250 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 250 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 250 * 3600000).toISOString()
  },
  {
    id: 'job-haca-127',
    jobCode: 'JOB-2026-027',
    title: 'Django Backend Developer',
    company: 'Blinkit Tech',
    location: 'Hyderabad, Telangana, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹7,00,000 - ₹10,00,000 / annum',
    description: 'Implement ORM queries, database models, and authentication workflows in Django.',
    requiredSkills: ["Python","Django","SQL","PostgreSQL"],
    preferredSkills: ["Git","Docker","REST APIs"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Python Development"],
    category: 'Backend Development',
    normalizedDesignation: 'Backend Developer',
    sourceChannel: 'PLACEMENT_DIRECT',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Django%20Backend%20Developer%20Blinkit%20Tech',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Django%20Backend%20Developer%20Blinkit%20Tech',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 260 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 260 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 260 * 3600000).toISOString()
  },
  {
    id: 'job-haca-128',
    jobCode: 'JOB-2026-028',
    title: 'Associate Backend Developer',
    company: 'BharatPe Labs',
    location: 'Pune, Maharashtra, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹5,50,000 - ₹8,00,000 / annum',
    description: 'Entry-level backend role creating data endpoints, writing unit tests, and optimizing queries.',
    requiredSkills: ["Python","SQL","Git","REST APIs"],
    preferredSkills: ["FastAPI","Node.js","PostgreSQL"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Python Development","Full Stack Web Development"],
    category: 'Backend Development',
    normalizedDesignation: 'Backend Developer',
    sourceChannel: 'AI_JOB_SCRAPER',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Associate%20Backend%20Developer%20BharatPe%20Labs',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Associate%20Backend%20Developer%20BharatPe%20Labs',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 270 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 270 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 270 * 3600000).toISOString()
  },
  {
    id: 'job-haca-129',
    jobCode: 'JOB-2026-029',
    title: 'Backend Systems Engineer',
    company: 'PhonePe Tech',
    location: 'Chennai, Tamil Nadu, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹8,50,000 - ₹13,00,000 / annum',
    description: 'Architect event-driven server workflows and high-concurrency database connection pools.',
    requiredSkills: ["Node.js","TypeScript","SQL","Docker"],
    preferredSkills: ["PostgreSQL","Redis","AWS"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Backend Development',
    normalizedDesignation: 'Backend Developer',
    sourceChannel: 'ATS_JOB_API',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Backend%20Systems%20Engineer%20PhonePe%20Tech',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Backend%20Systems%20Engineer%20PhonePe%20Tech',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 280 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 280 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 280 * 3600000).toISOString()
  },
  {
    id: 'job-haca-130',
    jobCode: 'JOB-2026-030',
    title: 'Python Server Developer',
    company: 'Ola Electric Tech',
    location: 'Mumbai, Maharashtra, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹7,50,000 - ₹11,50,000 / annum',
    description: 'Engineer cloud-native microservices with Python, containerization, and automated test pipelines.',
    requiredSkills: ["Python","FastAPI","SQL","Docker"],
    preferredSkills: ["PostgreSQL","Git","Linux"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Python Development"],
    category: 'Backend Development',
    normalizedDesignation: 'Backend Developer',
    sourceChannel: 'PLACEMENT_DIRECT',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Python%20Server%20Developer%20Ola%20Electric%20Tech',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Python%20Server%20Developer%20Ola%20Electric%20Tech',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 290 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 290 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 290 * 3600000).toISOString()
  },
  {
    id: 'job-haca-131',
    jobCode: 'JOB-2026-031',
    title: 'Data Analyst',
    company: 'Apex Software Labs',
    location: 'Gurugram, Haryana, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹6,50,000 - ₹9,50,000 / annum',
    description: 'Transform raw business data into actionable BI dashboards, metrics models, and executive reports.',
    requiredSkills: ["Python","SQL","Power BI","Excel"],
    preferredSkills: ["Tableau","Pandas","Data Analysis"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Data Analytics"],
    category: 'Data Analytics',
    normalizedDesignation: 'Data Analyst',
    sourceChannel: 'AI_JOB_SCRAPER',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Data%20Analyst%20Apex%20Software%20Labs',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Data%20Analyst%20Apex%20Software%20Labs',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 300 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 300 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 300 * 3600000).toISOString()
  },
  {
    id: 'job-haca-132',
    jobCode: 'JOB-2026-032',
    title: 'Business Intelligence Analyst',
    company: 'NovaTech Digital',
    location: 'Noida, Uttar Pradesh, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹7,00,000 - ₹10,50,000 / annum',
    description: 'Create executive dashboards, data models, and KPI trackers for senior leadership and operations.',
    requiredSkills: ["SQL","Power BI","Excel","Data Analysis"],
    preferredSkills: ["Python","Tableau","Data Visualization"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Data Analytics"],
    category: 'Data Analytics',
    normalizedDesignation: 'Data Analyst',
    sourceChannel: 'ATS_JOB_API',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Business%20Intelligence%20Analyst%20NovaTech%20Digital',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Business%20Intelligence%20Analyst%20NovaTech%20Digital',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 310 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 310 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 310 * 3600000).toISOString()
  },
  {
    id: 'job-haca-133',
    jobCode: 'JOB-2026-033',
    title: 'Junior Data Analyst',
    company: 'DataStream Systems',
    location: 'Remote - India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹5,50,000 - ₹8,00,000 / annum',
    description: 'Analyze core product metrics, run SQL queries, and synthesize actionable analytical findings.',
    requiredSkills: ["SQL","Python","Excel","Power BI"],
    preferredSkills: ["Pandas","Git","Tableau"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Data Analytics"],
    category: 'Data Analytics',
    normalizedDesignation: 'Data Analyst',
    sourceChannel: 'PLACEMENT_DIRECT',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Junior%20Data%20Analyst%20DataStream%20Systems',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Junior%20Data%20Analyst%20DataStream%20Systems',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 320 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 320 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 320 * 3600000).toISOString()
  },
  {
    id: 'job-haca-134',
    jobCode: 'JOB-2026-034',
    title: 'Product Data Analyst',
    company: 'Vanguard Analytics',
    location: 'Thiruvananthapuram, Kerala, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹7,50,000 - ₹11,00,000 / annum',
    description: 'Collaborate with product squads to analyze user retention, conversion funnels, and feature usage.',
    requiredSkills: ["SQL","Python","Power BI","Data Analysis"],
    preferredSkills: ["Excel","Tableau","Statistics"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Data Analytics"],
    category: 'Data Analytics',
    normalizedDesignation: 'Data Analyst',
    sourceChannel: 'AI_JOB_SCRAPER',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Product%20Data%20Analyst%20Vanguard%20Analytics',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Product%20Data%20Analyst%20Vanguard%20Analytics',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 330 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 330 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 330 * 3600000).toISOString()
  },
  {
    id: 'job-haca-135',
    jobCode: 'JOB-2026-035',
    title: 'SQL Data Analyst',
    company: 'PixelCraft Studio',
    location: 'Kozhikode, Kerala, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹6,00,000 - ₹9,00,000 / annum',
    description: 'Write advanced SQL queries, window functions, and automate data extraction pipelines.',
    requiredSkills: ["SQL","Excel","Power BI","Python"],
    preferredSkills: ["PostgreSQL","Tableau","Data Analysis"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Data Analytics"],
    category: 'Data Analytics',
    normalizedDesignation: 'Data Analyst',
    sourceChannel: 'ATS_JOB_API',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=SQL%20Data%20Analyst%20PixelCraft%20Studio',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=SQL%20Data%20Analyst%20PixelCraft%20Studio',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 340 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 340 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 340 * 3600000).toISOString()
  },
  {
    id: 'job-haca-136',
    jobCode: 'JOB-2026-036',
    title: 'BI & Analytics Analyst',
    company: 'InfyCloud Technologies',
    location: 'Ernakulam, Kerala, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹6,00,000 - ₹8,50,000 / annum',
    description: 'Build interactive dashboards in Power BI and conduct ad-hoc data analysis across business units.',
    requiredSkills: ["Power BI","SQL","Excel","Data Visualization"],
    preferredSkills: ["Python","Pandas","Git"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Data Analytics"],
    category: 'Data Analytics',
    normalizedDesignation: 'Data Analyst',
    sourceChannel: 'PLACEMENT_DIRECT',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=BI%20%26%20Analytics%20Analyst%20InfyCloud%20Technologies',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=BI%20%26%20Analytics%20Analyst%20InfyCloud%20Technologies',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 350 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 350 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 350 * 3600000).toISOString()
  },
  {
    id: 'job-haca-137',
    jobCode: 'JOB-2026-037',
    title: 'Operations Data Analyst',
    company: 'CyberNet Solutions',
    location: 'Bangalore, Karnataka, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹6,00,000 - ₹9,00,000 / annum',
    description: 'Provide operational intelligence, inventory tracking, and efficiency analysis through data.',
    requiredSkills: ["SQL","Excel","Python","Data Analysis"],
    preferredSkills: ["Power BI","Pandas","Tableau"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Data Analytics"],
    category: 'Data Analytics',
    normalizedDesignation: 'Data Analyst',
    sourceChannel: 'AI_JOB_SCRAPER',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Operations%20Data%20Analyst%20CyberNet%20Solutions',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Operations%20Data%20Analyst%20CyberNet%20Solutions',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 360 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 360 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 360 * 3600000).toISOString()
  },
  {
    id: 'job-haca-138',
    jobCode: 'JOB-2026-038',
    title: 'Associate Data Analyst',
    company: 'ZetaWave Labs',
    location: 'Kochi, Kerala, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹5,50,000 - ₹8,00,000 / annum',
    description: 'Entry-level analytics role extracting insights from databases and building stakeholder reports.',
    requiredSkills: ["Python","SQL","Excel","Power BI"],
    preferredSkills: ["Pandas","Tableau","Git"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Data Analytics"],
    category: 'Data Analytics',
    normalizedDesignation: 'Data Analyst',
    sourceChannel: 'ATS_JOB_API',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Associate%20Data%20Analyst%20ZetaWave%20Labs',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Associate%20Data%20Analyst%20ZetaWave%20Labs',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 370 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 370 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 370 * 3600000).toISOString()
  },
  {
    id: 'job-haca-139',
    jobCode: 'JOB-2026-039',
    title: 'AI / Machine Learning Engineer',
    company: 'Thoughtworks India',
    location: 'Hyderabad, Telangana, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹9,00,000 - ₹15,00,000 / annum',
    description: 'Train, evaluate, and deploy predictive machine learning models and NLP pipelines.',
    requiredSkills: ["Python","Machine Learning","TensorFlow","SQL"],
    preferredSkills: ["PyTorch","Scikit-learn","Docker","NLP"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Python Development","Data Analytics"],
    category: 'AI / Machine Learning',
    normalizedDesignation: 'AI / Machine Learning Engineer',
    sourceChannel: 'PLACEMENT_DIRECT',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=AI%20%2F%20Machine%20Learning%20Engineer%20Thoughtworks%20India',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=AI%20%2F%20Machine%20Learning%20Engineer%20Thoughtworks%20India',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 380 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 380 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 380 * 3600000).toISOString()
  },
  {
    id: 'job-haca-140',
    jobCode: 'JOB-2026-040',
    title: 'Machine Learning Associate',
    company: 'Freshworks India',
    location: 'Pune, Maharashtra, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹7,50,000 - ₹11,50,000 / annum',
    description: 'Prepare training datasets, benchmark model metrics, and build intelligent inference APIs.',
    requiredSkills: ["Python","Machine Learning","Data Analysis","SQL"],
    preferredSkills: ["PyTorch","Pandas","Docker"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Python Development","Data Analytics"],
    category: 'AI / Machine Learning',
    normalizedDesignation: 'AI / Machine Learning Engineer',
    sourceChannel: 'AI_JOB_SCRAPER',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Machine%20Learning%20Associate%20Freshworks%20India',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Machine%20Learning%20Associate%20Freshworks%20India',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 390 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 390 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 390 * 3600000).toISOString()
  },
  {
    id: 'job-haca-141',
    jobCode: 'JOB-2026-041',
    title: 'Junior AI Engineer',
    company: 'Zoho Corporation',
    location: 'Chennai, Tamil Nadu, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹7,00,000 - ₹11,00,000 / annum',
    description: 'Implement intelligent algorithms, LLM integrations, and classification models.',
    requiredSkills: ["Python","Machine Learning","SQL","Git"],
    preferredSkills: ["TensorFlow","PyTorch","Docker"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Python Development","Data Analytics"],
    category: 'AI / Machine Learning',
    normalizedDesignation: 'AI / Machine Learning Engineer',
    sourceChannel: 'ATS_JOB_API',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Junior%20AI%20Engineer%20Zoho%20Corporation',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Junior%20AI%20Engineer%20Zoho%20Corporation',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 400 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 400 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 400 * 3600000).toISOString()
  },
  {
    id: 'job-haca-142',
    jobCode: 'JOB-2026-042',
    title: 'Data Scientist Associate',
    company: 'Swiggy Tech',
    location: 'Mumbai, Maharashtra, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹8,00,000 - ₹12,00,000 / annum',
    description: 'Conduct statistical testing, build predictive features, and visualize machine learning outcomes.',
    requiredSkills: ["Python","Machine Learning","SQL","Data Analysis"],
    preferredSkills: ["Pandas","Scikit-learn","Statistics"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Data Analytics","Python Development"],
    category: 'AI / Machine Learning',
    normalizedDesignation: 'AI / Machine Learning Engineer',
    sourceChannel: 'PLACEMENT_DIRECT',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Data%20Scientist%20Associate%20Swiggy%20Tech',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Data%20Scientist%20Associate%20Swiggy%20Tech',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 410 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 410 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 410 * 3600000).toISOString()
  },
  {
    id: 'job-haca-143',
    jobCode: 'JOB-2026-043',
    title: 'DevOps Engineer',
    company: 'Razorpay Labs',
    location: 'Gurugram, Haryana, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹8,50,000 - ₹13,50,000 / annum',
    description: 'Automate build pipelines, container orchestration, and cloud infrastructure monitoring.',
    requiredSkills: ["Docker","Kubernetes","AWS","Git"],
    preferredSkills: ["Linux","CI/CD","Terraform","Python"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Cloud / DevOps',
    normalizedDesignation: 'DevOps Engineer',
    sourceChannel: 'AI_JOB_SCRAPER',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=DevOps%20Engineer%20Razorpay%20Labs',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=DevOps%20Engineer%20Razorpay%20Labs',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 420 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 420 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 420 * 3600000).toISOString()
  },
  {
    id: 'job-haca-144',
    jobCode: 'JOB-2026-044',
    title: 'Cloud Infrastructure Associate',
    company: 'Meesho Engineering',
    location: 'Noida, Uttar Pradesh, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹7,00,000 - ₹10,50,000 / annum',
    description: 'Maintain high-availability cloud servers, automated backups, and deployment scripts.',
    requiredSkills: ["AWS","Docker","Linux","Git"],
    preferredSkills: ["Kubernetes","Python","CI/CD"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Cloud / DevOps',
    normalizedDesignation: 'DevOps Engineer',
    sourceChannel: 'ATS_JOB_API',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Cloud%20Infrastructure%20Associate%20Meesho%20Engineering',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Cloud%20Infrastructure%20Associate%20Meesho%20Engineering',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 430 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 430 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 430 * 3600000).toISOString()
  },
  {
    id: 'job-haca-145',
    jobCode: 'JOB-2026-045',
    title: 'Junior DevOps Engineer',
    company: 'CRED Tech',
    location: 'Remote - India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹6,50,000 - ₹9,50,000 / annum',
    description: 'Support CI/CD automation, monitor server performance metrics, and manage Docker containers.',
    requiredSkills: ["Docker","Linux","Git","AWS"],
    preferredSkills: ["CI/CD","Python","SQL"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Cloud / DevOps',
    normalizedDesignation: 'DevOps Engineer',
    sourceChannel: 'PLACEMENT_DIRECT',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Junior%20DevOps%20Engineer%20CRED%20Tech',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Junior%20DevOps%20Engineer%20CRED%20Tech',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 440 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 440 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 440 * 3600000).toISOString()
  },
  {
    id: 'job-haca-146',
    jobCode: 'JOB-2026-046',
    title: 'Site Reliability Engineer (SRE)',
    company: 'InMobi Digital',
    location: 'Thiruvananthapuram, Kerala, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹8,50,000 - ₹14,00,000 / annum',
    description: 'Ensure platform reliability, uptime monitoring, latency optimization, and disaster recovery.',
    requiredSkills: ["AWS","Docker","Linux","Python"],
    preferredSkills: ["Kubernetes","Git","CI/CD"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'Cloud / DevOps',
    normalizedDesignation: 'DevOps Engineer',
    sourceChannel: 'AI_JOB_SCRAPER',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Site%20Reliability%20Engineer%20(SRE)%20InMobi%20Digital',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Site%20Reliability%20Engineer%20(SRE)%20InMobi%20Digital',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 450 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 450 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 450 * 3600000).toISOString()
  },
  {
    id: 'job-haca-147',
    jobCode: 'JOB-2026-047',
    title: 'UI/UX Designer',
    company: 'Groww Labs',
    location: 'Kozhikode, Kerala, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹6,00,000 - ₹9,50,000 / annum',
    description: 'Design engaging user experiences, design systems, and responsive desktop/mobile flows in Figma.',
    requiredSkills: ["Figma","Wireframing","Prototyping","User Research"],
    preferredSkills: ["Design Systems","Product Design","HTML5"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech', 'School of Design'],
    eligiblePrograms: ["UI/UX Product Design"],
    category: 'UI/UX / Product Design',
    normalizedDesignation: 'UI/UX Designer',
    sourceChannel: 'ATS_JOB_API',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=UI%2FUX%20Designer%20Groww%20Labs',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=UI%2FUX%20Designer%20Groww%20Labs',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 460 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 460 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 460 * 3600000).toISOString()
  },
  {
    id: 'job-haca-148',
    jobCode: 'JOB-2026-048',
    title: 'Product Designer (UI/UX)',
    company: 'Zerodha Tech',
    location: 'Ernakulam, Kerala, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹7,00,000 - ₹11,00,000 / annum',
    description: 'Lead product design initiatives, run usability feedback sessions, and build reusable UI design kits.',
    requiredSkills: ["Figma","UI/UX","Design Systems","Prototyping"],
    preferredSkills: ["User Research","Wireframing","CSS3"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech', 'School of Design'],
    eligiblePrograms: ["UI/UX Product Design"],
    category: 'UI/UX / Product Design',
    normalizedDesignation: 'UI/UX Designer',
    sourceChannel: 'PLACEMENT_DIRECT',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Product%20Designer%20(UI%2FUX)%20Zerodha%20Tech',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Product%20Designer%20(UI%2FUX)%20Zerodha%20Tech',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 470 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 470 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 470 * 3600000).toISOString()
  },
  {
    id: 'job-haca-149',
    jobCode: 'JOB-2026-049',
    title: 'QA Automation Engineer',
    company: 'Postman Software',
    location: 'Bangalore, Karnataka, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹6,50,000 - ₹9,50,000 / annum',
    description: 'Develop end-to-end automated test suites, regression test scripts, and integration validations.',
    requiredSkills: ["JavaScript","Selenium","Jest","Git"],
    preferredSkills: ["Cypress","Playwright","Python","REST APIs"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'QA / Testing',
    normalizedDesignation: 'QA / Test Engineer',
    sourceChannel: 'AI_JOB_SCRAPER',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=QA%20Automation%20Engineer%20Postman%20Software',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=QA%20Automation%20Engineer%20Postman%20Software',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 480 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 480 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 480 * 3600000).toISOString()
  },
  {
    id: 'job-haca-150',
    jobCode: 'JOB-2026-050',
    title: 'Software Test Engineer',
    company: 'Hasura Tech',
    location: 'Kochi, Kerala, India',
    countryCode: 'IN',
    employmentType: 'FULL_TIME',
    experienceRequirement: '0–1 year (Entry Level)',
    minExperienceYears: 0,
    salaryRange: '₹6,00,000 - ₹8,50,000 / annum',
    description: 'Execute functional, regression, and API tests to maintain strict software quality standards.',
    requiredSkills: ["Selenium","SQL","Git","JavaScript"],
    preferredSkills: ["Cypress","Jest","Postman"],
    educationRequirements: ['HACA Certificate or relevant Bachelor Degree in Tech'],
    eligibleSchools: ['School of Tech'],
    eligiblePrograms: ["Full Stack Web Development"],
    category: 'QA / Testing',
    normalizedDesignation: 'QA / Test Engineer',
    sourceChannel: 'ATS_JOB_API',
    externalUrl: 'https://www.linkedin.com/jobs/search/?keywords=Software%20Test%20Engineer%20Hasura%20Tech',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Software%20Test%20Engineer%20Hasura%20Tech',
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    status: 'ACTIVE',
    discoveredAt: new Date(Date.now() - 490 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 490 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 490 * 3600000).toISOString()
  }
];

export const INITIAL_APPLICATIONS: JobApplication[] = [];

export const INITIAL_REJECTION_FEEDBACK: RejectionFeedbackRecord[] = [];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-001',
    actorId: 'user-root-admin',
    actorName: 'Executive Administrator (HACA Root)',
    actorRole: 'MAIN_ADMIN',
    action: 'SYSTEM_BOOTSTRAP',
    entityType: 'SYSTEM',
    entityId: 'ROOT',
    details: 'HACA Centralized Placement System initialized with Single Main Admin Governance model.',
    timestamp: '2026-01-01T00:00:00Z'
  },
  {
    id: 'audit-002',
    actorId: 'user-root-admin',
    actorName: 'Executive Administrator (HACA Root)',
    actorRole: 'MAIN_ADMIN',
    action: 'USER_PROVISION',
    entityType: 'USER',
    entityId: 'user-po-1',
    details: 'Provisioned Placement Officer account for Asad Rizvi.',
    timestamp: '2026-01-05T08:00:00Z'
  },
  {
    id: 'audit-003',
    actorId: 'user-root-admin',
    actorName: 'Executive Administrator (HACA Root)',
    actorRole: 'MAIN_ADMIN',
    action: 'ELIGIBILITY_TOGGLED',
    entityType: 'STUDENT',
    entityId: 'student-tech-1',
    details: 'Main Admin approved student Ali Raza for placement eligibility (Attendance: 94%, Capstone: 95%).',
    timestamp: '2026-02-01T10:00:00Z'
  },
  {
    id: 'audit-004',
    actorId: 'user-root-admin',
    actorName: 'Executive Administrator (HACA Root)',
    actorRole: 'MAIN_ADMIN',
    action: 'EMERGENCY_ELIGIBILITY_OVERRIDE',
    entityType: 'STUDENT',
    entityId: 'student-mkt-1',
    details: 'Main Admin emergency override executed for Bilal Ahmed (Reason: Prior agency experience validated by HACA Board).',
    timestamp: '2026-02-12T09:15:00Z'
  }
];

export const INITIAL_APIFY_CONFIG: ApifyScraperConfig = {
  actorId: 'haca-placement/job-board-scraper',
  apiKey: 'apify_sec_live_998124801bfe49',
  targetBoards: ['LinkedIn Jobs India', 'Naukri', 'Indeed India', 'Instahyre'],
  scheduleCron: '0 4 * * *', // Daily 4 AM
  isEnabled: true,
  lastRunTimestamp: '2026-02-11T05:00:00Z',
  leadsProcessedTotal: 48
};

export const INITIAL_LMS_CONFIG: LmsSyncConfig = {
  endpoint: 'https://lms.haca.edu/api/v1/sync',
  apiKey: 'lms_bearer_live_8819401824aa',
  autoSyncIntervalMinutes: 60,
  lastSyncTimestamp: '2026-02-12T00:00:00Z',
  totalRecordsSynced: 126,
  status: 'CONNECTED'
};

export const INITIAL_ATS_CONFIG: AtsSyncConfig = {
  isEnabled: true,
  greenhouseBoards: ['postman', 'inmobi', 'groww', 'cloudflare', 'stripe', 'figma', 'github', 'reddit'],
  leverCompanies: ['meesho', 'cred', 'netflix', 'spotify', 'palantir'],
  ashbyCompanies: ['linear', 'ramp', 'notion', 'retool'],
  lastRunTimestamp: undefined,
  leadsProcessedTotal: 0
};

